const $ = (selector, element = document) => element.querySelector(selector);
const rulesElement = $("#rules");
let state = { enabled: true, rules: [] };
const makeRule = () => ({ id: crypto.randomUUID(), enabled: true, name: "New API mock", match: { urlPattern: "https://api.example.com/*", method: "*" }, request: { url: "", method: "", headers: "{}", body: "" }, response: { enabled: true, status: 200, statusText: "OK", headers: '{"content-type":"application/json"}', body: "{}", delayMs: 0 } });
const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;" }[c]));
const ruleTemplate = (rule) => `<article class="rule" data-id="${rule.id}"><div class="rule-head"><input class="rule-enabled" type="checkbox" ${rule.enabled ? "checked" : ""}><input data-path="name" type="text" value="${esc(rule.name)}"><button class="delete" type="button">Delete</button></div><div class="fields"><label>URL pattern (* wildcard)<input data-path="match.urlPattern" value="${esc(rule.match.urlPattern)}"></label><label>Method<select data-path="match.method">${["*","GET","POST","PUT","PATCH","DELETE","HEAD"].map((m) => `<option ${rule.match.method === m ? "selected" : ""}>${m}</option>`).join("")}</select></label></div><div class="request"><span class="section-title">Request override (applies if no mock response)</span><div class="fields"><label>Replacement URL (optional)<input data-path="request.url" value="${esc(rule.request.url)}"></label><label>Replacement method (optional)<input data-path="request.method" value="${esc(rule.request.method)}"></label></div><label>Headers JSON — empty/null value removes a header<textarea data-path="request.headers">${esc(rule.request.headers)}</textarea></label><label>Replacement body (optional)<textarea data-path="request.body">${esc(rule.request.body)}</textarea></label></div><div class="response"><label><input class="response-enabled" type="checkbox" ${rule.response.enabled ? "checked" : ""}> Return mock response instead of real API</label><div class="fields"><label>Status<input data-path="response.status" type="number" value="${esc(rule.response.status)}"></label><label>Delay ms<input data-path="response.delayMs" type="number" value="${esc(rule.response.delayMs)}"></label></div><label>Response headers JSON<textarea data-path="response.headers">${esc(rule.response.headers)}</textarea></label><label>Response body<textarea data-path="response.body">${esc(rule.response.body)}</textarea></label></div></article>`;
function readPath(object, path) { return path.split(".").reduce((value, key) => value[key], object); }
function writePath(object, path, value) { const parts = path.split("."); const last = parts.pop(); parts.reduce((target, key) => target[key], object)[last] = value; }
function render() { rulesElement.innerHTML = state.rules.map(ruleTemplate).join(""); }
function persist() { chrome.storage.local.set(state); }
$("#enabled").addEventListener("change", (event) => { state.enabled = event.target.checked; persist(); });
$("#add").addEventListener("click", () => { state.rules.push(makeRule()); render(); persist(); });
rulesElement.addEventListener("input", (event) => { const rule = state.rules.find((item) => item.id === event.target.closest(".rule")?.dataset.id); if (rule && event.target.dataset.path) { writePath(rule, event.target.dataset.path, event.target.type === "number" ? Number(event.target.value) : event.target.value); persist(); } });
rulesElement.addEventListener("change", (event) => { const rule = state.rules.find((item) => item.id === event.target.closest(".rule")?.dataset.id); if (!rule) return; if (event.target.classList.contains("rule-enabled")) rule.enabled = event.target.checked; if (event.target.classList.contains("response-enabled")) rule.response.enabled = event.target.checked; persist(); });
rulesElement.addEventListener("click", (event) => { if (!event.target.classList.contains("delete")) return; state.rules = state.rules.filter((item) => item.id !== event.target.closest(".rule").dataset.id); render(); persist(); });
chrome.storage.local.get(state, (saved) => { state = saved; $("#enabled").checked = state.enabled; render(); });
